/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VeChungToiRouteImport } from './routes/ve-chung-toi'
import { Route as LienHeRouteImport } from './routes/lien-he'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DichVuQuangCaoRouteImport } from './routes/dich-vu/quang-cao'
import { Route as DichVuGiaiPhapPhanMemRouteImport } from './routes/dich-vu/giai-phap-phan-mem'
import { Route as DichVuChuyenDoiSoRouteImport } from './routes/dich-vu/chuyen-doi-so'
import { Route as DichVuBanWebsiteRouteImport } from './routes/dich-vu/ban-website'

const VeChungToiRoute = VeChungToiRouteImport.update({
  id: '/ve-chung-toi',
  path: '/ve-chung-toi',
  getParentRoute: () => rootRouteImport,
} as any)
const LienHeRoute = LienHeRouteImport.update({
  id: '/lien-he',
  path: '/lien-he',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DichVuQuangCaoRoute = DichVuQuangCaoRouteImport.update({
  id: '/dich-vu/quang-cao',
  path: '/dich-vu/quang-cao',
  getParentRoute: () => rootRouteImport,
} as any)
const DichVuGiaiPhapPhanMemRoute = DichVuGiaiPhapPhanMemRouteImport.update({
  id: '/dich-vu/giai-phap-phan-mem',
  path: '/dich-vu/giai-phap-phan-mem',
  getParentRoute: () => rootRouteImport,
} as any)
const DichVuChuyenDoiSoRoute = DichVuChuyenDoiSoRouteImport.update({
  id: '/dich-vu/chuyen-doi-so',
  path: '/dich-vu/chuyen-doi-so',
  getParentRoute: () => rootRouteImport,
} as any)
const DichVuBanWebsiteRoute = DichVuBanWebsiteRouteImport.update({
  id: '/dich-vu/ban-website',
  path: '/dich-vu/ban-website',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/lien-he': typeof LienHeRoute
  '/ve-chung-toi': typeof VeChungToiRoute
  '/dich-vu/ban-website': typeof DichVuBanWebsiteRoute
  '/dich-vu/chuyen-doi-so': typeof DichVuChuyenDoiSoRoute
  '/dich-vu/giai-phap-phan-mem': typeof DichVuGiaiPhapPhanMemRoute
  '/dich-vu/quang-cao': typeof DichVuQuangCaoRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/lien-he': typeof LienHeRoute
  '/ve-chung-toi': typeof VeChungToiRoute
  '/dich-vu/ban-website': typeof DichVuBanWebsiteRoute
  '/dich-vu/chuyen-doi-so': typeof DichVuChuyenDoiSoRoute
  '/dich-vu/giai-phap-phan-mem': typeof DichVuGiaiPhapPhanMemRoute
  '/dich-vu/quang-cao': typeof DichVuQuangCaoRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/lien-he': typeof LienHeRoute
  '/ve-chung-toi': typeof VeChungToiRoute
  '/dich-vu/ban-website': typeof DichVuBanWebsiteRoute
  '/dich-vu/chuyen-doi-so': typeof DichVuChuyenDoiSoRoute
  '/dich-vu/giai-phap-phan-mem': typeof DichVuGiaiPhapPhanMemRoute
  '/dich-vu/quang-cao': typeof DichVuQuangCaoRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/lien-he'
    | '/ve-chung-toi'
    | '/dich-vu/ban-website'
    | '/dich-vu/chuyen-doi-so'
    | '/dich-vu/giai-phap-phan-mem'
    | '/dich-vu/quang-cao'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/lien-he'
    | '/ve-chung-toi'
    | '/dich-vu/ban-website'
    | '/dich-vu/chuyen-doi-so'
    | '/dich-vu/giai-phap-phan-mem'
    | '/dich-vu/quang-cao'
  id:
    | '__root__'
    | '/'
    | '/lien-he'
    | '/ve-chung-toi'
    | '/dich-vu/ban-website'
    | '/dich-vu/chuyen-doi-so'
    | '/dich-vu/giai-phap-phan-mem'
    | '/dich-vu/quang-cao'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LienHeRoute: typeof LienHeRoute
  VeChungToiRoute: typeof VeChungToiRoute
  DichVuBanWebsiteRoute: typeof DichVuBanWebsiteRoute
  DichVuChuyenDoiSoRoute: typeof DichVuChuyenDoiSoRoute
  DichVuGiaiPhapPhanMemRoute: typeof DichVuGiaiPhapPhanMemRoute
  DichVuQuangCaoRoute: typeof DichVuQuangCaoRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/ve-chung-toi': {
      id: '/ve-chung-toi'
      path: '/ve-chung-toi'
      fullPath: '/ve-chung-toi'
      preLoaderRoute: typeof VeChungToiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lien-he': {
      id: '/lien-he'
      path: '/lien-he'
      fullPath: '/lien-he'
      preLoaderRoute: typeof LienHeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dich-vu/quang-cao': {
      id: '/dich-vu/quang-cao'
      path: '/dich-vu/quang-cao'
      fullPath: '/dich-vu/quang-cao'
      preLoaderRoute: typeof DichVuQuangCaoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dich-vu/giai-phap-phan-mem': {
      id: '/dich-vu/giai-phap-phan-mem'
      path: '/dich-vu/giai-phap-phan-mem'
      fullPath: '/dich-vu/giai-phap-phan-mem'
      preLoaderRoute: typeof DichVuGiaiPhapPhanMemRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dich-vu/chuyen-doi-so': {
      id: '/dich-vu/chuyen-doi-so'
      path: '/dich-vu/chuyen-doi-so'
      fullPath: '/dich-vu/chuyen-doi-so'
      preLoaderRoute: typeof DichVuChuyenDoiSoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dich-vu/ban-website': {
      id: '/dich-vu/ban-website'
      path: '/dich-vu/ban-website'
      fullPath: '/dich-vu/ban-website'
      preLoaderRoute: typeof DichVuBanWebsiteRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LienHeRoute: LienHeRoute,
  VeChungToiRoute: VeChungToiRoute,
  DichVuBanWebsiteRoute: DichVuBanWebsiteRoute,
  DichVuChuyenDoiSoRoute: DichVuChuyenDoiSoRoute,
  DichVuGiaiPhapPhanMemRoute: DichVuGiaiPhapPhanMemRoute,
  DichVuQuangCaoRoute: DichVuQuangCaoRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
